### ISSUE TITLE
Error when trying to train the model on NWPU VHR dataset

### ISSUE THREAD

**Issue by Ismaildata** [ming71/CFC-Net#17]
Epoch   gpu_mem       ref       cls       reg     total   targets  img_size
  0% 0/260 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/torch/cuda/memory.py:393: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  FutureWarning)
     0/100     2.42G      1.26      2.07      1.18       4.5         6       416:  15% 40/260 [00:24<02:13,  1.65it/s]
Traceback (most recent call last):
  File "/content/drive/MyDrive/CFC-Net/train.py", line 316, in <module>
    train_model(arg, hyps)
  File "/content/drive/MyDrive/CFC-Net/train.py", line 160, in train_model
    losses = model(ims, gt_boxes,process =epoch/epochs )
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/CFC-Net/models/model.py", line 102, in forward
    cls_feats = self.cls_attention(features, process)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/CFC-Net/models/fpn.py", line 305, in forward
    atten_ft = self.channel_att(fp) * self.spatial_att(fp)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/CFC-Net/models/fpn.py", line 265, in forward
    return self.gate_c(avg_pool).unsqueeze(2).unsqueeze(3).expand_as(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x512 and 256x16)

**Comment by ming71** [comment]
It seems there is something wrong with the input feature. You can set a breakpoint to check shape of featmaps.
